<?php
// +----------------------------------------------------------------------
// | CRMEB [ CRMEB tiếp sức cho nhà phát triển, hỗ trợ doanh nghiệp phát triển ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016~2023 https://www.crmeb.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed CRMEB không phải là phần mềm tự do, không được phép gỡ bỏ bản quyền liên quan đến CRMEB khi chưa được cho phép
// +----------------------------------------------------------------------
// | Author: CRMEB Team <admin@crmeb.com>
// +----------------------------------------------------------------------

namespace crmeb\services\express\storage;

use app\services\shipping\ExpressServices;
use crmeb\exceptions\ApiException;
use crmeb\services\express\BaseExpress;
use crmeb\exceptions\AdminException;

/**
 * Class Express
 * @package crmeb\services\express\storage
 */
class Express extends BaseExpress
{
    //Đăng ký dịch vụ
    const EXPRESS_OPEN = 'v2/expr/open';
    //Mẫu vận đơn điện tử
    const EXPRESS_TEMP = 'v2/expr_dump/temp';
    //Đơn vị vận chuyển
    const EXPRESS_LIST = 'v2/expr/express';
    //Tra cứu vận đơn
    const EXPRESS_QUERY = 'v2/expr/query';
    //In vận đơn
    const EXPRESS_DUMP = 'v2/expr/dump';
    //Lấy thông tin đơn vị vận chuyển
    const SHIPMENT_KUAIDI_NUMS = 'v2/shipment/get_kuaidi_coms';
    //Tạo đơn gửi hàng của merchant
    const SHIPMENT_CREATE_ORDER = 'v2/shipment/create_order';
    //Hủy yêu cầu gửi hàng của người bán
    const SHIPMENT_CANCEL_ORDER = 'v2/shipment/cancel_order';
    //Lấy danh sách đơn gửi hàng của merchant
    const SHIPMENT_INDEX = 'v2/shipment/index';
    //Lấy số tiền tạm giữ của đơn gửi hàng merchant
    const SHIPMENT_PRICE = 'v2/shipment/price';

    /**
     * Khởi tạo
     * @param array $config
     * @return mixed|void
     */
    protected function initialize(array $config = [])
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    /**
     * Lấy đơn vị vận chuyển cho gửi hàng merchant
     * @return array|mixed
     * @author Deng Fenglai
     * @email 136327134@qq.com
     * @date 2023/5/15
     */
    public function getKuaidiComs()
    {
        $list = $this->accessToken->httpRequest(self::SHIPMENT_KUAIDI_NUMS, [], 'GET');
        foreach ($list as &$item) {
            $item['code'] = $item['value'];
            $item['value'] = $item['label'];
            $num = 1;
            foreach ($item['list'] as &$value) {
                $value['title'] = $item['label'] . 'mẫu' . $num;
                $num++;
            }
        }
        return $list;
    }

    /**
     * Tạo đơn gửi hàng merchant
     * @param array $data
     * @return array|mixed
     * @author Deng Fenglai
     * @email 136327134@qq.com
     * @date 2023/5/15
     */
    public function shippmentCreateOrder(array $data)
    {
        $siid = sys_config('config_export_siid');
        $param = [
            'kuaidicom' => $data['kuaidicom'],
            'man_name' => $data['man_name'],
            'phone' => $data['phone'],
            'address' => $data['address'],
            'send_real_name' => $data['send_real_name'],
            'send_phone' => $data['send_phone'],
            'send_address' => $data['send_address'],
            'call_back_url' => sys_config('site_url') . '/api/order_call_back',
            'return_type' => $siid ? '10' : '20',
            'siid' => $siid,
            'tempid' => $data['temp_id'],
            'cargo' => $data['cargo'],
            'weight' => $data['weight'],
            'day_type' => $data['day_type'],
            'pickup_start_time' => $data['pickup_start_time'],
            'pickup_end_time' => $data['pickup_end_time'],
        ];
        return $this->accessToken->httpRequest(self::SHIPMENT_CREATE_ORDER, $param, 'post');
    }

    /**
     * Hủy đơn gửi hàng merchant
     * @param array $data
     * @return array|mixed
     * @author Deng Fenglai
     * @email 136327134@qq.com
     * @date 2023/5/15
     */
    public function shipmentCancelOrder(array $data)
    {
        $param = [
            'task_id' => $data['task_id'],//id nhiệm vụ gửi hàng merchant của Kuaidi100
            'order_id' => $data['order_id'],//Mã đơn hàng do gửi hàng merchant của Kuaidi100 khởi tạo. Không phải mã đơn hàng trong hệ thống
            'cancel_msg' => $data['cancel_msg'],//Lý do hủy
        ];
        return $this->accessToken->httpRequest(self::SHIPMENT_CANCEL_ORDER, $param);
    }

    /**
     * Lấy danh sách đơn gửi hàng của merchant
     * @param array $data
     * @return array|mixed
     * @author Deng Fenglai
     * @email 136327134@qq.com
     * @date 2023/5/15
     */
    public function getShipmentOrderList(array $data)
    {
        $param = [
            'kuaidi_num' => $data['kuaidi_num'] ?? '',
            'courier_name' => $data['courier_name'] ?? '',
            'page' => $data['page'] ?? 1,
            'limit' => $data['limit'] ?? 10,
        ];

        return $this->accessToken->httpRequest(self::SHIPMENT_INDEX, $param, 'GET');
    }

    /**
     * @param array $data
     * @return array|mixed
     * @author Deng Fenglai
     * @email 136327134@qq.com
     * @date 2023/6/16
     */
    public function getPrice(array $data)
    {
        if (empty($data['kuaidicom'])) {
            throw new ApiException('Mã đơn vị vận chuyển là bắt buộc');
        }
        if (empty($data['send_address'])) {
            throw new ApiException('Địa chỉ gửi hàng là bắt buộc');
        }
        if (empty($data['address'])) {
            throw new ApiException('Địa chỉ nhận hàng là bắt buộc');
        }
        $param = [
            'kuaidicom' => $data['kuaidicom'],
            'send_address' => $data['send_address'],
            'address' => $data['address'] ?? '',
            'weight' => $data['weight'] ?? '',
            'service_type' => $data['service_type'] ?? '',
        ];

        return $this->accessToken->httpRequest(self::SHIPMENT_PRICE, $param);
    }

    /**
     * Mở dịch vụ vận chuyển
     * @return bool|mixed
     */
    public function open()
    {
        return $this->accessToken->httpRequest(self::EXPRESS_OPEN, []);
    }

    /**
     * Lấy mẫu vận đơn điện tử
     * @param $com Mã đơn vị vận chuyển
     * @param int $page
     * @param int $limit
     * @return bool|mixed
     */
    public function temp(string $com)
    {
        $param = [
            'com' => $com
        ];

        $header = [];
        if (!sys_config('config_export_siid')) {
            $header = ['version:v1.1'];
        }
        return $this->accessToken->httpRequest(self::EXPRESS_TEMP, $param, 'GET', true, $header);
    }

    /**
     * Lấy danh sách đơn vị vận chuyển
     * @param int $type Loại vận chuyển: 1, đơn vị vận chuyển nội địa; 2, đơn vị vận chuyển quốc tế; 3, bưu chính quốc tế
     * @return bool|mixed
     */
    public function express(int $type = 0, int $page = 0, int $limit = 20)
    {
        if ($type) {
            $param = [
                'type' => $type,
                'page' => $page,
                'limit' => $limit
            ];
        } else {
            $param = [];
        }

        return $this->accessToken->httpRequest(self::EXPRESS_LIST, $param, 'GET');
    }

    /**
     * Truy vấn thông tin vận chuyển
     * @param $com
     * @param $num
     * @return bool|mixed
     * @return Có ký nhận không - ischeck
     * @return Trạng thái vận chuyển: status 0 đang vận chuyển, 1 đã lấy hàng, 2 gặp vấn đề, 3 đã ký nhận, 4 từ chối ký nhận, 5 đang phát hàng, 6 hoàn trả, 7 chuyển đơn, 10 chờ thông quan, 11 đang thông quan, 12 đã thông quan, 13 thông quan bất thường, 14 người nhận từ chối ký nhận
     * @return Chi tiết vận chuyển - content
     */
    public function query(string $num, string $com = '', $phone = '')
    {
        $param = [
            'com' => $com,
            'num' => $num,
            'phone' => $phone
        ];
        if ($com === null) {
            unset($param['com']);
        }
        return $this->accessToken->httpRequest(self::EXPRESS_QUERY, $param, 'post');
    }

    /**
     * In vận đơn điện tử
     * @param array $data Tham số bắt buộc: com (mã đơn vị vận chuyển), to_name (người gửi), to_tel (điện thoại người gửi), to_addr (địa chỉ chi tiết người gửi), from_name (người nhận), from_tel (điện thoại người nhận), from_addr (địa chỉ người nhận), temp_id (ID mẫu vận đơn điện tử), siid (mã máy in cloud), count (số lượng sản phẩm)
     * @return bool|mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\DbException
     * @throws \think\db\exception\ModelNotFoundException
     */
    public function dump($data)
    {
        $param = $data;
        $param['com'] = $data['com'] ?? '';
        if (!$param['com']) throw new AdminException(400713);
        $param['to_name'] = $data['to_name'] ?? '';
        $param['to_tel'] = $data['to_tel'] ?? '';
        $param['order_id'] = $data['order_id'] ?? '';
        $param['to_addr'] = $data['to_addr'] ?? '';
        if (!$param['to_addr'] || !$param['to_tel'] || !$param['to_name']) throw new AdminException(400714);
        $param['from_name'] = $data['from_name'] ?? '';
        $param['from_tel'] = $data['from_tel'] ?? '';
        $param['from_addr'] = $data['from_addr'] ?? '';
        if (!$param['from_name'] || !$param['from_tel'] || !$param['from_addr']) throw new AdminException(400715);
        $param['temp_id'] = $data['temp_id'] ?? '';
        if (!$param['temp_id']) {
            throw new AdminException(400712);
        }
        $param['siid'] = sys_config('config_export_siid');
//        if (!$param['siid']) {
//            throw new AdminException(400716);
//        }
        $param['count'] = $data['count'] ?? '';
        $param['cargo'] = $data['cargo'] ?? '';
        if (!$param['count']) {
            throw new AdminException(400717);
        }
        /** @var ExpressServices $expressServices */
        $expressServices = app()->make(ExpressServices::class);
        $expressData = $expressServices->getOneByWhere(['code' => $param['com']])->toArray();
        if (isset($data['cargo'])) $param['cargo'] = $data['cargo'];
        if ($expressData['partner_id'] == 1) $param['partner_id'] = $expressData['account'];
        if ($expressData['partner_key'] == 1) $param['partner_key'] = $expressData['key'];
        if ($expressData['net'] == 1) $param['net'] = $expressData['net_name'];
        if ($expressData['check_man'] == 1) $param['checkMan'] = $expressData['courier_name'];
        if ($expressData['partner_name'] == 1) $param['partnerName'] = $expressData['customer_name'];
        if ($expressData['is_code'] == 1) $param['code'] = $expressData['code_name'];
        if (!$data['siid']) {
            $param['print_type'] = 'IMAGE';
        }
        $header = [];
        if (!sys_config('config_export_siid')) {
            $header = ['version:v1.1'];
        }
        return $this->accessToken->httpRequest(self::EXPRESS_DUMP, $param, 'POST', true, $header);
    }

}
