<?php
// +----------------------------------------------------------------------
// | CRMEB [ CRMEB tiếp sức cho nhà phát triển, hỗ trợ doanh nghiệp phát triển ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016~2023 https://www.crmeb.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed CRMEB không phải là phần mềm tự do, không được phép gỡ bỏ bản quyền liên quan đến CRMEB khi chưa được cho phép
// +----------------------------------------------------------------------
// | Author: CRMEB Team <admin@crmeb.com>
// +----------------------------------------------------------------------

namespace crmeb\services\template\storage;


use crmeb\services\template\BaseMessage;

class Baidu extends BaseMessage
{
    /**
     * Khởi tạo
     * @param array $config
     * @return mixed|void
     */
    protected function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    /**
     * Gửi tin nhắn mẫu
     * @param string $templateId
     * @param array $data
     * @return mixed|void
     */
    public function send(string $templateId, array $data = [])
    {
        // TODO: Implement send() method.
    }

    /**
     * Thêm tin nhắn mẫu
     * @param string $shortId
     * @return mixed|void
     */
    public function add(string $shortId)
    {
        // TODO: Implement add() method.
    }

    /**
     * Xóa tin nhắn mẫu
     * @param string $templateId
     * @return mixed|void
     */
    public function delete(string $templateId)
    {
        // TODO: Implement delete() method.
    }

    /**
     * Danh sách tin nhắn mẫu
     * @return mixed|void
     */
    public function list()
    {
        // TODO: Implement list() method.
    }
}
