<?php
// +----------------------------------------------------------------------
// | CRMEB [ CRMEB tiếp sức cho nhà phát triển, hỗ trợ doanh nghiệp phát triển ]
// +----------------------------------------------------------------------
// | Copyright (c) 2016~2023 https://www.crmeb.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed CRMEB không phải là phần mềm tự do, không được phép gỡ bỏ bản quyền liên quan đến CRMEB khi chưa được cho phép
// +----------------------------------------------------------------------
// | Author: CRMEB Team <admin@crmeb.com>
// +----------------------------------------------------------------------
namespace crmeb\services\template\storage;

use app\services\message\SystemNotificationServices;
use crmeb\services\template\BaseMessage;
use crmeb\services\app\WechatService;
use think\facade\Log;

class Wechat extends BaseMessage
{
    protected $error;

    /**
     * Khởi tạo
     * @param array $config
     * @return mixed|void
     */
    protected function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $templateId
     * @return mixed
     */
    public function getTempId(string $templateId)
    {
        return app()->make(SystemNotificationServices::class)->value(['wechat_tempkey' => $templateId], 'wechat_tempid');
    }

    /**
     * Gửi tin nhắn
     * @param string $tempid
     * @param array $data
     * @return bool|mixed
     */
    public function send(string $tempid, array $data = [], $wechatToRoutine = 0)
    {
        if (!$tempid) {
            return $this->setError('Template ID does not exist');
        }
        if (!$this->openId) {
            return $this->setError('Openid does not exist');
        }
        try {
            $res = WechatService::sendTemplate($this->openId, $tempid, $data, $this->toUrl, $this->color, $wechatToRoutine);
            $this->clear();
            return $res;
        } catch (\Exception $e) {
            Log::error('Gửi đến openid:' . $this->openId . 'tin nhắn mẫu WeChat thất bại, ID mẫu:' . $tempid . '; lý do lỗi:' . $e->getMessage());
            return $this->setError($e->getMessage());
        }
    }

    /**
     * Lấy tất cả mẫu
     * @return \EasyWeChat\Support\Collection|mixed
     */
    public function list()
    {
        return WechatService::noticeService()->getPrivateTemplates();
    }

    /**
     * Thêm tin nhắn mẫu
     * @param string $shortId
     * @return \EasyWeChat\Support\Collection|mixed
     */
    public function add(string $shortId)
    {
        return WechatService::noticeService()->addTemplate($shortId);
    }

    /**
     * Xóa tin nhắn mẫu
     * @param string $templateId
     * @return \EasyWeChat\Support\Collection|mixed
     */
    public function delete(string $templateId)
    {
        return WechatService::noticeService()->deletePrivateTemplate($templateId);
    }

    /**
     * Trả về danh sách tất cả ngành được hỗ trợ
     * @return \EasyWeChat\Support\Collection
     */
    public function getIndustry()
    {
        return WechatService::noticeService()->getIndustry();
    }

    /**
     * Đặt ngành cho tin nhắn mẫu
     * @return \EasyWeChat\Support\Collection
     */
    public function setIndustry($one, $two)
    {
        return WechatService::noticeService()->setIndustry($one, $two);
    }

    /**
     * Đặt thông tin lỗi
     * @param string|null $error
     * @return bool
     */
    protected function setError(?string $error = null)
    {
        $this->error = $error ?: 'Lỗi không xác định';
        return false;
    }

    /**
     * Lấy thông tin lỗi
     * @return string
     */
    public function getError()
    {
        $error = $this->error;
        $this->error = null;
        return $error;
    }
}
